# Generated by Django 2.2.13 on 2020-12-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201221_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uid',
        ),
    ]
