# Generated by Django 2.2.13 on 2020-12-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='updated_user',
        ),
    ]
